Revert "etc: use ${DOCUMENTS} macro where appropriate"
This reverts commit 5df1f27c638c487dfd664ea3a0f756565e1e57bd.

That commit breaks things, as pointed out by @rusty-snake[1]:

> @kmk3 @glitsj16 The xdg macros are treated literally if they have sub
> components (#2359):
>
> ```
> Error: "${DOCUMENTS}/KeePassXC" is an invalid filename: rejected character: "{"
> ```

[1]: https://github.com/netblue30/firejail/commit/3fa2927c3c1c5cf583864746538ea791c1ba2dc4#commitcomment-46913219