Do not declare variable in for loop
Caused build failure in Travis (due to lack of C99 mode):

sbox.c: In function ‘sbox_run_v’:

sbox.c:185:3: error: ‘for’ loop initial declarations are only allowed in C99 mode

   for (int i = 3; i < max; i++)

   ^

sbox.c:185:3: note: use option -std=c99 or -std=gnu99 to compile your code