build: fix running make clean with undefined vars
In the `debian_ci` job in .gitlab-ci.yml, dpkg-deb calls `make
distclean` before calling ./configure, which makes `make clean` fail due
to certain variables not being declared:

     dpkg-source -i -I --before-build .
    [...]
       dh_auto_clean
    	make -j2 distclean
    make[1]: Entering directory '/builds/kmk3/firejail_ci'
    error: run ./configure to generate config.mk
    [...]
    rm -f contrib/syntax/files/example [...]
    rm -fr - -.tar.xz
    rm: invalid option -- '.'
    Try 'rm --help' for more information.
    make[1]: *** [Makefile:175: clean] Error 1

This amends commit 8a783cdc2 ("build: use TARNAME and remove more paths
on clean", 2023-07-29) / PR #6186.