fnetlock: fix unused bw variable warning
This is breaking build-clang on CI[1]:

    make -C src/fnetlock/
    make[1]: Entering directory '/home/runner/work/firejail/firejail/src/fnetlock'
    clang-14 [...] -c main.c -o main.o
    main.c:97:11: error: variable 'bw' set but not used [-Werror,-Wunused-but-set-variable]
            unsigned bw = 0; // bandwidth calculations
                     ^
    1 error generated.
    make[1]: *** [../../src/prog.mk:16: main.o] Error 1
    make: *** [Makefile:58: src/fnetlock/fnetlock] Error 2

Added on commit 8e4b847cd ("split nettrace executable ^Cto netrace and
netlock", 2023-07-25).

[1]: https://github.com/netblue30/firejail/actions/runs/5669072674/job/15361026508

Cc: @netblue30