modif: rlimit: improve error messages (#6893)
Changes:

* Remove unrelated `strerror` output from some error messages
* Remove periods from some error messages
* Ensure that the invalid value is in the error message
* Ensure that the full command name is in the error message (instead of
  just `rlimit` in some cases)
* Standardize output
* tests: Expect the full command name (and argument in some cases)

Examples:

Before:

    $ firejail --quiet --noprofile --rlimit-cpu=-1 /bin/true
    Error: invalid rlimit -1
    $ firejail --quiet --noprofile --rlimit-nproc=-1 /bin/true
    Error: invalid rlimit -1
    $ firejail --quiet --noprofile --rlimit-as=-1 /bin/true
    Error: invalid rlimit-as. Only use positive numbers and K, M or G suffix.: No such file or directory

After:

    $ firejail --quiet --noprofile --rlimit-cpu=-1 /bin/true
    Error: invalid rlimit-cpu: -1
    $ firejail --quiet --noprofile --rlimit-nproc=-1 /bin/true
    Error: invalid rlimit-nproc: -1
    $ firejail --quiet --noprofile --rlimit-as=-1 /bin/true
    Error: invalid rlimit-as: -1; use only positive numbers and K, M or G suffix

This is a follow-up to #6891.

Relates to #4315.