build: prevent make clean error if compile.sh --clean fails
In the `debian_ci` job in .gitlab-ci.yml, dpkg-deb calls `make
distclean` before calling ./configure, which makes `make clean` fail due
to test/compile/compile.sh not being able to source config.mk (which is
created by ./configure):

     dpkg-source -i -I --before-build .
    [...]
       dh_auto_clean
    	make -j2 distclean
    make[1]: Entering directory '/builds/Firejail/firejail_ci'
    error: run ./configure to generate config.mk
    [...]
    cd compile && ./compile.sh --clean
    ./compile.sh: line 15: ./../../config.sh: No such file or directory
    make[2]: *** [Makefile:24: clean] Error 1

This amends commit 152a21f15 ("build: simplify clean target",
2023-07-29) / PR #6186.