landlock: use uint32_t instead of __u32 in firejail.h
The build on Alpine fails due to `__u32` not being defined.  It seems
that musl itself does not define it, so linux/types.h would have to be
included (for example, by including linux/landlock.h).

Error from `build_src_package`[1]:

    make -C src/firejail/
    make[1]: Entering directory '/builds/Firejail/firejail_ci/src/firejail'
    gcc [...] -DMOD_DIR='"src/firejail"' [...] -c appimage.c -o appimage.o
    In file included from appimage.c:23:
    firejail.h:977:17: error: unknown type name '__u32'
      977 | int ll_restrict(__u32 flags);
          |                 ^~~~~
    make[1]: Leaving directory '/builds/Firejail/firejail_ci/src/firejail'
    make[1]: *** [../../src/prog.mk:16: appimage.o] Error 1
    make: *** [Makefile:58: src/firejail/firejail] Error 2

This amends commit 13b2c566d ("feature: add Landlock support",
2023-10-24) / PR #6078.

[1] https://gitlab.com/Firejail/firejail_ci/-/jobs/5729692038