feature: use non-blocking flock calls (#6750)
As reported by @hlein in #6729, if a firejailed process is `^Z`'d at the
wrong time during startup, other firejail processes will be unable to
proceed because they'll wait forever for an flock on
`/run/firejail/firejail-run.lock`.

This builds upon f4b8c6d to add a busy wait while attempting to
acquire a lock. This allows the application to bail out if it fails
to acquire a lock after a given timeout.

Behavior after this patch (we use SIGSTOP, as that cannot be caught/ignored):

```sh
$ firejail --debug id & P=$!;sleep 0.00001;kill -STOP $P
[1] 14411
Looking for kernel processes
Found kthreadd process, we are not running in a sandbox
pid=14411: locking /run/firejail/firejail-run.lock ...
pid=14411: locked /run/firejail/firejail-run.lock

[1]+  Stopped                 firejail --debug id
$ firejail --debug ls
Looking for kernel processes
Found kthreadd process, we are not running in a sandbox
pid=14413: locking /run/firejail/firejail-run.lock ...
pid=14413: sleeping 500us while waiting on lock
pid=14413: sleeping 1000us while waiting on lock
pid=14413: sleeping 2000us while waiting on lock
pid=14413: sleeping 4000us while waiting on lock
pid=14413: sleeping 8000us while waiting on lock
pid=14413: sleeping 16000us while waiting on lock
pid=14413: sleeping 32000us while waiting on lock
pid=14413: sleeping 64000us while waiting on lock
pid=14413: sleeping 128000us while waiting on lock
pid=14413: sleeping 256000us while waiting on lock
pid=14413: sleeping 512000us while waiting on lock
pid=14413: sleeping 1000000us while waiting on lock
pid=14413: sleeping 1000000us while waiting on lock
pid=14413: sleeping 1000000us while waiting on lock
pid=14413: sleeping 1000000us while waiting on lock
Error: timeout occurred while waiting for lock /run/firejail/firejail-run.lock
Error: ../../src/firejail/preproc.c:114: preproc_lock_file: flock: Resource temporarily unavailable
```

Enhances f4b8c6d.

Suggested-by: @hlein