Adding sort.py to GitLab CI (#2973)
* Add contrib/sort.py to Gitlab CI

Not adding to Debian Jessie or CentOS since python >=3.6 is not
available

See https://github.com/netblue30/firejail/pull/2870

* Updates

Explicitly install python3 on Ubuntu (should be pre-installed but not
working as-is)

Remove running python3 code on CentOS

* ci: comment out contrib/sort.py for Alpine

Getting this error:
$ python3 contrib/sort.py etc/*.{profile,inc}
[ Error ] Can't find `etc/*.{profile,inc}'
ERROR: Job failed: exit code 1

For now it's better to debug later and enable this test for the other
jobs