ci: disable build_src_package GitLab job due to libtrace errors
Build log[1]:

    $ make
    [...]
    make -C src/libtrace/
    make[1]: Entering directory '/builds/Firejail/firejail_ci/src/libtrace'
    gcc -ggdb -O2 -DVERSION='"0.9.73"' [...]  -c ../../src/libtrace/libtrace.c -o ../../src/libtrace/libtrace.o
    ../../src/libtrace/libtrace.c:451:59: warning: 'struct stat64' declared inside parameter list will not be visible outside of this definition or declaration
      451 | typedef int (*orig_stat64_t)(const char *pathname, struct stat64 *statbuf);
          |                                                           ^~~~~~
    ../../src/libtrace/libtrace.c:453:41: warning: 'struct stat64' declared inside parameter list will not be visible outside of this definition or declaration
      453 | int stat64(const char *pathname, struct stat64 *statbuf) {
          |                                         ^~~~~~
    ../../src/libtrace/libtrace.c: In function 'stat64':
    ../../src/libtrace/libtrace.c:457:40: error: passing argument 2 of 'orig_stat64' from incompatible pointer type [-Wincompatible-pointer-types]
      457 |         int rv = orig_stat64(pathname, statbuf);
          |                                        ^~~~~~~
          |                                        |
          |                                        struct stat64 *
    ../../src/libtrace/libtrace.c:457:40: note: expected 'struct stat64 *' but argument is of type 'struct stat64 *'
    ../../src/libtrace/libtrace.c: At top level:
    ../../src/libtrace/libtrace.c:476:60: warning: 'struct stat64' declared inside parameter list will not be visible outside of this definition or declaration
      476 | typedef int (*orig_lstat64_t)(const char *pathname, struct stat64 *statbuf);
          |                                                            ^~~~~~
    ../../src/libtrace/libtrace.c:478:42: warning: 'struct stat64' declared inside parameter list will not be visible outside of this definition or declaration
      478 | int lstat64(const char *pathname, struct stat64 *statbuf) {
          |                                          ^~~~~~
    ../../src/libtrace/libtrace.c: In function 'lstat64':
    ../../src/libtrace/libtrace.c:482:41: error: passing argument 2 of 'orig_lstat64' from incompatible pointer type [-Wincompatible-pointer-types]
      482 |         int rv = orig_lstat64(pathname, statbuf);
          |                                         ^~~~~~~
          |                                         |
          |                                         struct stat64 *
    ../../src/libtrace/libtrace.c:482:41: note: expected 'struct stat64 *' but argument is of type 'struct stat64 *'
    make[1]: Leaving directory '/builds/Firejail/firejail_ci/src/libtrace'

Environment: gcc (14.2.0-r4), musl-dev (1.2.5-r8) on Alpine Linux v3.21.

Relates to #6610.

[1] https://gitlab.com/Firejail/firejail_ci/-/jobs/8853165146