obs.profile: allow lua
Some plugins may require it[1]:

    error: os_dlopen([...]): libluajit-5.1.so.2: [...]: Permission denied

    warning: Module '/usr//lib/obs-plugins/frontend-tools.so' not loaded

[1] https://github.com/netblue30/firejail/issues/6130#issue-2040800338