profiles: add keep-hostname to noprofile.profile
Related to this, trying to open xorg programs stopped working on Arch
recently (even with `--profile=noprofile`), producing the following
error[1]:

    $ /usr/local/bin/thunderbird
    [...]
    Authorization required, but no authorization protocol specified

    Error: cannot open display: :0

    Parent is shutting down, bye...

The programs work if `--keep-hostname` is used.

The workaround was found quickly, but mostly by luck and guesswork, as
needing to use a profile command when even `--profile=noprofile` does
not work is counterintuitive and unexpected.

Related commits:

* cc8b019b5 ("--keep-hostname part 1 (#7048)", 2026-02-03)
* e31d872a5 ("profiles: add keep-hostname to profile.template",
  2026-02-11)

Relates to #7062.

[1] https://github.com/netblue30/firejail/issues/7062#issue-3943568845