ci: test: build with --enable-chroot
Make sure to enable it before running chroot-related tests.

This fixes CI errors[1]:

    make -C test chroot
    make[1]: Entering directory '/home/runner/work/firejail/firejail/test'
    cd chroot && ./chroot.sh 2>&1 | tee chroot.log
    chown: invalid user: 'netblue:netblue'
    chown: invalid user: 'netblue:netblue'
    cp: cannot stat '/home/netblue/.Xauthority': No such file or directory
    	not a dynamic executable
    	not a dynamic executable
    	not a dynamic executable
    To enter the chroot directory run: firejail --chroot=/tmp/chroot
    TESTING: chroot disabled (test/chroot/fs_chroot_disabled.exp)
    spawn /bin/bash
    firejail
    runner@runnervmos4r4:~/work/firejail/firejail/test/chroot$
    <irejail/test/chroot$ firejail
    Error: invalid --chroot=/tmp/chroot command line option
    runner@runnervmos4r4:~/work/firejail/firejail/test/chroot$ TESTING ERROR 0

    TESTING: chroot (test/chroot/fs_chroot.exp)
    spawn /bin/bash
    firejail
    runner@runnervmos4r4:~/work/firejail/firejail/test/chroot$
    <irejail/test/chroot$ firejail
    Error: invalid --chroot=/tmp/chroot command line option
    runner@runnervmos4r4:~/work/firejail/firejail/test/chroot$ TESTING ERROR 0

This amends commit c7b8bd894 ("disable by default --chroot feature at
compile time; use ./configure --enable-chroot to enable this feature",
2026-07-14).

Relates to #7202.

[1] hhttps://github.com/netblue30/firejail/actions/runs/29350288303/job/87144468576yder365