modif: improve new network namespace error message
Clarify that `--net` should be used to create a new network namespace
before using a firejail command that needs to be executed inside a
(firejail) network namespace.

Example:

    $ firejail --netfilter.print=10000
    Switching to pid 10001, the first child process inside the sandbox
    Error: the sandbox doesn't use a new network namespace (see --net)

Reported-by: @osevan

Relates to #6820.