feature: use non-blocking flock calls
As reported by @hlein in #6729, if a firejailed process is `^Z`'d at the
wrong time during startup, other firejail processes will be unable to
proceed because they'll wait forever for an flock on
`/run/firejail/firejail-run.lock`.

This builds upon commit f4b8c6dbb ("bugfix: fix potential deadlock with
flock + SIGTSTP (#6750)", 2025-05-21) to add a busy wait while
attempting to acquire a lock. This allows the application to bail out if
it fails to acquire a lock after a given timeout.

Behavior after this patch (we use SIGSTOP, as that cannot be
caught/ignored):

    $ firejail --debug id & P=$!;sleep 0.00001;kill -STOP $P
    [1] 14411
    Looking for kernel processes
    Found kthreadd process, we are not running in a sandbox
    pid=14411: locking /run/firejail/firejail-run.lock ...
    pid=14411: locked /run/firejail/firejail-run.lock

    [1]+  Stopped                 firejail --debug id
    $ firejail --debug ls
    Looking for kernel processes
    Found kthreadd process, we are not running in a sandbox
    pid=14413: locking /run/firejail/firejail-run.lock ...
    pid=14413: sleeping 500us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 1000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 2000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 4000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 8000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 16000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 32000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 64000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 128000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 256000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    pid=14413: sleeping 500000us while trying to lock /run/firejail/firejail-run.lock
    Error: timeout occurred while trying to lock /run/firejail/firejail-run.lock
    Error: ../../src/firejail/preproc.c:112: preproc_lock_file: flock: Resource temporarily unavailable

Enhances commit f4b8c6dbb ("bugfix: fix potential deadlock with flock +
SIGTSTP (#6750)", 2025-05-21).

Suggested-by: @hlein
Co-authored-by: @kmk3