vmware.profile: snapshot requires /etc/mtab
This patch avoid the following error:
Error: One of the parameters supplied is invalid

Tested with VMware Workstation 16.2.4